image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

tasks:
  - init: make run

vscode:
  extensions:
    - sumneko.lua@0.15.4:v9ELO/hl++dbpsIqPq/7Mg==